from tkinter import *
import functions

root = Tk()
root.title('Calculator v 1.0')
root.resizable(0, 0)
txtBox = Text(root, height=5, width=60, wrap=WORD, state=DISABLED)
btn1 = Button(root, text="1", command=lambda: functions.inp_to_txtb(1))
btn2 = Button(root, text="2", command=lambda: functions.inp_to_txtb(2))
btn3 = Button(root, text="3", command=lambda: functions.inp_to_txtb(3))
btn4 = Button(root, text="4", command=lambda: functions.inp_to_txtb(4))
btn5 = Button(root, text="5", command=lambda: functions.inp_to_txtb(5))
btn6 = Button(root, text="6", command=lambda: functions.inp_to_txtb(6))
btn7 = Button(root, text="7", command=lambda: functions.inp_to_txtb(7))
btn8 = Button(root, text="8", command=lambda: functions.inp_to_txtb(8))
btn9 = Button(root, text="9", command=lambda: functions.inp_to_txtb(9))
btn0 = Button(root, text="0", command=lambda: functions.inp_to_txtb(0))
btnDot = Button(root, text=".", command=lambda: functions.inp_to_txtb('.'))
btnBackspace = Button(root, text="|<", command=lambda: functions.backspace())
btnExponentiation = Button(root, text="^", command=lambda: functions.inp_to_txtb('**'))
btnEqual = Button(root, text="=", bg='gray60', command=lambda: functions.equal())
btnAdd = Button(root, text="+", command=lambda: functions.inp_to_txtb('+'))
btnSubtract = Button(root, text="-", command=lambda: functions.inp_to_txtb('-'))
btnMultiply = Button(root, text="*", command=lambda: functions.inp_to_txtb('*'))
btnDivide = Button(root, text="/", command=lambda: functions.inp_to_txtb('/'))
btnClean = Button(root, text="C", command=lambda: functions.clean())
btnParenthesisL = Button(root, text="(", command=lambda: functions.inp_to_txtb('('))
btnParenthesisR = Button(root, text=")", command=lambda: functions.inp_to_txtb(')'))
# not done yet
btnLog = Button(root, text="ln()", command=lambda: functions.inp_to_txtb('log('))
txtBox.grid(row=0, column=0, columnspan=5, sticky=W+E)
btn1.grid(row=1, column=0, sticky=W+E)
btn2.grid(row=1, column=1, sticky=W+E)
btn3.grid(row=1, column=2, sticky=W+E)
btn4.grid(row=2, column=0, sticky=W+E)
btn5.grid(row=2, column=1, sticky=W+E)
btn6.grid(row=2, column=2, sticky=W+E)
btn7.grid(row=3, column=0, sticky=W+E)
btn8.grid(row=3, column=1, sticky=W+E)
btn9.grid(row=3, column=2, sticky=W+E)
btn0.grid(row=4, column=0, sticky=W+E)
btnLog.grid(row=5, column=0, sticky=W+E)
btnDot.grid(row=4, column=1, sticky=W+E)
btnBackspace.grid(row=4, column=2, sticky=W+E)
btnExponentiation.grid(row=4, column=4, sticky=W+E)
btnEqual.grid(row=5, column=3, columnspan=2, sticky=W+E)
btnAdd.grid(row=1, column=3, sticky=W+E)
btnSubtract.grid(row=2, column=3, sticky=W+E)
btnMultiply.grid(row=3, column=3, sticky=W+E)
btnDivide.grid(row=4, column=3, sticky=W+E)
btnClean.grid(row=1, column=4, sticky=W+E)
btnParenthesisL.grid(row=2, column=4, sticky=W+E)
btnParenthesisR.grid(row=3, column=4, sticky=W+E)


def gui_start():
    root.mainloop()
