from tkinter import *
import functions

root = Tk()
root.title('Calculator v 1.1')
# root.geometry("500x300")
root.resizable(0, 0)
# height = root.winfo_screenheight()
# width = root.winfo_screenwidth()
# f1 = Frame(root, height=height, width=width)
txtBox = Text(root, height=5, width=50, wrap=WORD, state=DISABLED)
btn1 = Button(root, text="1", width=10, command=lambda: functions.inp_to_txtb(1))
btn2 = Button(root, text="2", width=10, command=lambda: functions.inp_to_txtb(2))
btn3 = Button(root, text="3", width=10, command=lambda: functions.inp_to_txtb(3))
btn4 = Button(root, text="4", width=10, command=lambda: functions.inp_to_txtb(4))
btn5 = Button(root, text="5", width=10, command=lambda: functions.inp_to_txtb(5))
btn6 = Button(root, text="6", width=10, command=lambda: functions.inp_to_txtb(6))
btn7 = Button(root, text="7", width=10, command=lambda: functions.inp_to_txtb(7))
btn8 = Button(root, text="8", width=10, command=lambda: functions.inp_to_txtb(8))
btn9 = Button(root, text="9", width=10, command=lambda: functions.inp_to_txtb(9))
btn0 = Button(root, text="0", width=10, command=lambda: functions.inp_to_txtb(0))
btnDot = Button(root, text=".", width=10, command=lambda: functions.inp_to_txtb('.'))
btnBackspace = Button(root, text="|<", width=10, command=lambda: functions.backspace())
btnExponentiation = Button(root, text="^", width=10, command=lambda: functions.inp_to_txtb('**'))
btnEqual = Button(root, text="=", bg='gray60', width=50, command=lambda: functions.equal())
btnAdd = Button(root, text="+", width=10, command=lambda: functions.inp_to_txtb('+'))
btnSubtract = Button(root, text="-", width=10, command=lambda: functions.inp_to_txtb('-'))
btnMultiply = Button(root, text="*", width=10, command=lambda: functions.inp_to_txtb('*'))
btnDivide = Button(root, text="/", width=10, command=lambda: functions.inp_to_txtb('/'))
btnClean = Button(root, text="C", width=10, command=lambda: functions.clean())
btnParenthesisL = Button(root, text="(", width=10, command=lambda: functions.inp_to_txtb('('))
btnParenthesisR = Button(root, text=")", width=10, command=lambda: functions.inp_to_txtb(')'))
btnLog = Button(root, text="ln()", width=10, command=lambda: functions.inp_to_txtb('log('))
btnSqrt = Button(root, text="sq root", width=10, command=lambda: functions.inp_to_txtb('sqrt('))
btnSin = Button(root, text="sin()", width=10, command=lambda: functions.inp_to_txtb('sin('))
btnCos = Button(root, text="cos()", width=10, command=lambda: functions.inp_to_txtb('cos('))
txtBox.grid(row=0, column=0, columnspan=5, padx=5)
btn1.grid(row=1, column=0)
btn2.grid(row=1, column=1)
btn3.grid(row=1, column=2)
btn4.grid(row=2, column=0)
btn5.grid(row=2, column=1)
btn6.grid(row=2, column=2)
btn7.grid(row=3, column=0)
btn8.grid(row=3, column=1)
btn9.grid(row=3, column=2)
btn0.grid(row=4, column=0)
btnLog.grid(row=6, column=0)
btnSqrt.grid(row=6, column=1)
btnSin.grid(row=6, column=2)
btnCos.grid(row=6, column=3)
btnDot.grid(row=4, column=1)
btnBackspace.grid(row=2, column=3)
btnExponentiation.grid(row=4, column=2)
btnEqual.grid(row=7, column=0, columnspan=4, padx=5)
btnAdd.grid(row=5, column=0)
btnSubtract.grid(row=5, column=1)
btnMultiply.grid(row=5, column=2)
btnDivide.grid(row=5, column=3)
btnClean.grid(row=1, column=3)
btnParenthesisL.grid(row=3, column=3)
btnParenthesisR.grid(row=4, column=3)

# , sticky=W+E


def gui_start():
    root.mainloop()
